## 판다스는 문자열로 구성된 데이터에서 특정 문자열의 분할, 변경, 대체, 제거 등의 작업 가능
- str.split()
- str.upper()
- str.replace()
- str.contains()
- str.strip()

In [8]:
import pandas as pd
data = [['김예찬', 'm', '부장', '010-1234-5678', '서울시 강남구 삼성동'],
        ['이하은', 'f', '인턴', '010-8765-4321', '부산시 해운대구 우동'],
        ['박지현', 'f', '과장', '010-1357-2468', '대구시 수성구 범어동'],
        ['최준호', 'm', '임시', '010-1928-3746', '인천시 연수구 송도동'],
        ['김예서', 'f', '과장', '010-2846-5937', '천안시 서북구 두정동']
]
df= pd.DataFrame(data)
df.columns = ['성명', '성별', '직급', '전화번호', '주소']
df

    성명 성별  직급           전화번호           주소
0  김예찬  m  부장  010-1234-5678  서울시 강남구 삼성동
1  이하은  f  인턴  010-8765-4321  부산시 해운대구 우동
2  박지현  f  과장  010-1357-2468  대구시 수성구 범어동
3  최준호  m  임시  010-1928-3746  인천시 연수구 송도동
4  김예서  f  과장  010-2846-5937  천안시 서북구 두정동

In [9]:
# '성별' 컬룸에 있는 글씨를 대문자로 변경
df['성별']= df['성별'].str.upper()
df

    성명 성별  직급           전화번호           주소
0  김예찬  M  부장  010-1234-5678  서울시 강남구 삼성동
1  이하은  F  인턴  010-8765-4321  부산시 해운대구 우동
2  박지현  F  과장  010-1357-2468  대구시 수성구 범어동
3  최준호  M  임시  010-1928-3746  인천시 연수구 송도동
4  김예서  F  과장  010-2846-5937  천안시 서북구 두정동

In [10]:
# M-->male, F-->female 변경
df['성별']= df['성별'].str.replace('M','male')
df['성별']= df['성별'].str.replace('F','female')
df

    성명      성별  직급           전화번호           주소
0  김예찬    male  부장  010-1234-5678  서울시 강남구 삼성동
1  이하은  female  인턴  010-8765-4321  부산시 해운대구 우동
2  박지현  female  과장  010-1357-2468  대구시 수성구 범어동
3  최준호    male  임시  010-1928-3746  인천시 연수구 송도동
4  김예서  female  과장  010-2846-5937  천안시 서북구 두정동

In [11]:
# '직급' 에서 '인턴', '임시'를  '사원'으로 변경
df['직급'] = df['직급'].str.replace('인턴|임시','사원', regex=True) #정규표현식을 사용해야 | 연산 가능
df

    성명      성별  직급           전화번호           주소
0  김예찬    male  부장  010-1234-5678  서울시 강남구 삼성동
1  이하은  female  사원  010-8765-4321  부산시 해운대구 우동
2  박지현  female  과장  010-1357-2468  대구시 수성구 범어동
3  최준호    male  사원  010-1928-3746  인천시 연수구 송도동
4  김예서  female  과장  010-2846-5937  천안시 서북구 두정동

In [12]:
# '성별' 컬룸에서 '여성'을 찾기..있으면 True, 없으면 False
df['성별'].str.contains('female')

0    False
1     True
2     True
3    False
4     True
Name: 성별, dtype: bool

In [13]:
# 누군지 확인하기 위해 여성 데이터들만(True)인 요소들만 찾아서 추출--불리언 인덱싱
df[df['성별'].str.contains('female')]

    성명      성별  직급           전화번호           주소
1  이하은  female  사원  010-8765-4321  부산시 해운대구 우동
2  박지현  female  과장  010-1357-2468  대구시 수성구 범어동
4  김예서  female  과장  010-2846-5937  천안시 서북구 두정동

In [16]:
# 문자열의 슬라이스 기능
# 주소에서 도시명만 추출하여 도시컬룸 생성
df['도시'] = df['주소'].str[0:4]
df

    성명      성별  직급           전화번호           주소    도시
0  김예찬    male  부장  010-1234-5678  서울시 강남구 삼성동  서울시
1  이하은  female  사원  010-8765-4321  부산시 해운대구 우동  부산시
2  박지현  female  과장  010-1357-2468  대구시 수성구 범어동  대구시
3  최준호    male  사원  010-1928-3746  인천시 연수구 송도동  인천시
4  김예서  female  과장  010-2846-5937  천안시 서북구 두정동  천안시

In [17]:
#도시 중에서 서울시만 추출
seoul_df= df[ df['도시']=='서울시' ]
seoul_df

Empty DataFrame
Columns: [성명, 성별, 직급, 전화번호, 주소, 도시]
Index: []

In [18]:
aa= df.loc[0,'도시']
aa

'서울시 '

In [19]:
aa == '서울시'

False

In [20]:
aa.strip() == '서울시'

True

In [21]:
df['도시']= df['도시'].str.strip()
df

    성명      성별  직급           전화번호           주소   도시
0  김예찬    male  부장  010-1234-5678  서울시 강남구 삼성동  서울시
1  이하은  female  사원  010-8765-4321  부산시 해운대구 우동  부산시
2  박지현  female  과장  010-1357-2468  대구시 수성구 범어동  대구시
3  최준호    male  사원  010-1928-3746  인천시 연수구 송도동  인천시
4  김예서  female  과장  010-2846-5937  천안시 서북구 두정동  천안시

In [22]:
#도시 중에서 서울시만 추출
seoul_df= df[ df['도시']=='서울시' ]
seoul_df

    성명    성별  직급           전화번호           주소   도시
0  김예찬  male  부장  010-1234-5678  서울시 강남구 삼성동  서울시

In [23]:
# 특정 값들을 가진 파이썬 리스트의 항목을 가진 행들을 추출
cities= ['서울시','인천시']
seoul_incheon_df= df[ df['도시'].isin(cities) ]
seoul_incheon_df

    성명    성별  직급           전화번호           주소   도시
0  김예찬  male  부장  010-1234-5678  서울시 강남구 삼성동  서울시
3  최준호  male  사원  010-1928-3746  인천시 연수구 송도동  인천시

In [24]:
#서울,인천을 제외한 모든 도시들 추출 [ ~ Not ]
not_seoul_incheon_df= df[ ~(df['도시'].isin(cities)) ]
not_seoul_incheon_df

    성명      성별  직급           전화번호           주소   도시
1  이하은  female  사원  010-8765-4321  부산시 해운대구 우동  부산시
2  박지현  female  과장  010-1357-2468  대구시 수성구 범어동  대구시
4  김예서  female  과장  010-2846-5937  천안시 서북구 두정동  천안시

In [25]:
# 특정 글씨로 시작하는..
df[ df['성명'].str.startswith('최') ] #최로 시작하는..

    성명    성별  직급           전화번호           주소   도시
3  최준호  male  사원  010-1928-3746  인천시 연수구 송도동  인천시