## aggregation : 집계
집계는 여러 데이터를 하나의 요약된 결과로 결합하고 통계를 내는 과정.
sum, mean, min, max, std 등과 같은 연산으로 데이터를 분석하고 시각화하는 통계의 핵심 기능

In [1]:
# 1. groupby 실습

# 예) 부서별 지출 내역을 분석해서 회사의 재무 효율성을 높이는 데이터 분석 
import pandas as pd
df= pd.read_csv('./data_set/expense_data.csv')
df

         date department employee product  expense_amount  quantity
0  2025-01-01        영업팀      김민수     노트북         1200000         1
1  2025-01-01        영업팀      이서연     마우스           30000         3
2  2025-01-02       마케팅팀      박지훈   온라인광고          500000         1
3  2025-01-02        영업팀      김민수     모니터          400000         1
4  2025-01-03        개발팀      최은지    라이선스          800000         2
5  2025-01-03       마케팅팀      박지훈    이벤트비          200000         1
6  2025-01-04        영업팀      이서연     키보드          100000         2
7  2025-01-04        개발팀      최은지    서버비용         1500000         1
8  2025-01-05        영업팀      김민수     노트북         1200000         1
9  2025-01-05       마케팅팀      박지훈   온라인광고          700000         1

In [2]:
# 데이터 구조 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            10 non-null     object
 1   department      10 non-null     object
 2   employee        10 non-null     object
 3   product         10 non-null     object
 4   expense_amount  10 non-null     int64
 5   quantity        10 non-null     int64
dtypes: int64(2), object(4)
memory usage: 612.0+ bytes

In [4]:
# 데이터에서 어떤 부서들이 있는지 종류 확인해보기
df['department'].unique()

array(['영업팀', '마케팅팀', '개발팀'], dtype=object)

In [5]:
df['department'].nunique()

3

In [7]:
# 분석 시작!

# 부서별로 그룹화 하여 분석
dept= df.groupby('department')
dept # 데이터프레임이 아니고 데이터프레임을 그룹으로 묶은 객체가 출력됨

In [8]:
#그룹을 만드는 이유는 그룹별로 집계를 하기 위한 경우가 일반적.
dept.sum() #부서별 총 지출액 확인

,date,employee,product,expense_amount,quantity
department,,,,,
개발팀,2025-01-032025-01-04,최은지최은지,라이선스서버비용,2300000,3
마케팅팀,2025-01-022025-01-032025-01-05,박지훈박지훈박지훈,온라인광고이벤트비온라인광고,1400000,3
영업팀,2025-01-012025-01-012025-01-022025-01-042025-0...,김민수이서연김민수이서연김민수,노트북마우스모니터키보드노트북,2930000,8

In [9]:
# 수치데이터만 집계해야 하기에 특정 컬룸지정하여 집계
# 어느 부서의 지출이 가장 심한지 확인!
dept_df= df.groupby('department')['expense_amount'].sum().sort_values(ascending=False)
dept_df

department
영업팀     2930000
개발팀     2300000
마케팅팀    1400000
Name: expense_amount, dtype: int64

In [10]:
# 부서별로 어떤 항목으로 비용이 사용되는지 확인
df.groupby('department')['product']

In [11]:
df.groupby('department')['product'].sum()

department
개발팀            라이선스서버비용
마케팅팀     온라인광고이벤트비온라인광고
영업팀     노트북마우스모니터키보드노트북
Name: product, dtype: object

In [12]:
df.groupby('department')['product'].count() #항목 수

department
개발팀     2
마케팅팀    3
영업팀     5
Name: product, dtype: int64

In [13]:
df.groupby('department')['product'].unique() #구매항목 확인

department
개발팀             [라이선스, 서버비용]
마케팅팀           [온라인광고, 이벤트비]
영업팀     [노트북, 마우스, 모니터, 키보드]
Name: product, dtype: object

In [14]:
# 부서별. 항목별 지출비용 확인
dept_product_expense= df.groupby(['department','product'])['expense_amount'].sum()
dept_product_expense #series

department  product
개발팀         라이선스        800000
            서버비용       1500000
마케팅팀        온라인광고      1200000
            이벤트비        200000
영업팀         노트북        2400000
            마우스          30000
            모니터         400000
            키보드         100000
Name: expense_amount, dtype: int64

In [15]:
#데이터프레임으로 보고 싶다면..
dept_product_expense= df.groupby(['department','product'])['expense_amount'].sum().reset_index()
dept_product_expense

  department product  expense_amount
0        개발팀    라이선스          800000
1        개발팀    서버비용         1500000
2       마케팅팀   온라인광고         1200000
3       마케팅팀    이벤트비          200000
4        영업팀     노트북         2400000
5        영업팀     마우스           30000
6        영업팀     모니터          400000
7        영업팀     키보드          100000

In [16]:
#부서별. 항목별. 총지출액과 수량
dept_product_expense= df.groupby(['department','product'])[['expense_amount','quantity']].sum()
dept_product_expense

                    expense_amount  quantity
department product
개발팀        라이선스             800000         2
           서버비용            1500000         1
마케팅팀       온라인광고           1200000         2
           이벤트비             200000         1
영업팀        노트북             2400000         2
           마우스               30000         3
           모니터              400000         1
           키보드              100000         2

In [17]:
# 수량 대비 비용이 높은 부서 --> 단가 문제 확인
# 구매 단가 협상하는 대상으로 선별!!!

In [18]:
# 직원별 지출 규모 확인
employee_expense= df.groupby('employee')['expense_amount'].sum()
employee_expense

employee
김민수    2800000
박지훈    1400000
이서연     130000
최은지    2300000
Name: expense_amount, dtype: int64

In [19]:
# 비용 승인 프로세스 개선
# 특정 인원에 대한 비용 집중 여부 확인..

# 왜 총합만 보면 안되는 건지??
# 평균 지출이 높은 부서가 항상 문제일까?
# 수량 대비 금액 분석이 왜 필요한지???

집계함수의 종류에 대해 알아보기

In [20]:
df= pd.read_csv('./data_set/pandas2.csv')
df

    번호   성명  나이    몸무게         급여
0  100  김민재  27   75.0  5428000.0
1  101  이강인  22   57.0        NaN
2  102  박찬호  50   91.0  8428000.0
3  103  차범근  70    NaN  4428000.0
4  104  추신수  43  100.0  4528000.0
5  105  손흥민  31   72.0  7028000.0
6  106  황희찬  28   69.0  2528000.0

In [21]:
#데이터의 개수
df['급여'].count() # NaN을 제외한 개수

np.int64(6)

In [22]:
#데이터의 개수
df['급여'].size # NaN을 포함한 개수

7

In [23]:
#총합
df['급여'].sum()

np.float64(32368000.0)

In [24]:
#평균
df['급여'].mean()

np.float64(5394666.666666667)

In [25]:
#최고 연봉자
df['급여'].max()

8428000.0

In [26]:
#최저 연봉
df['급여'].min()

2528000.0

In [27]:
#표준 편차
df['급여'].std()

2086783.8092784472

In [28]:
#중위값
df['급여'].median()

4978000.0

In [29]:
#사분위 값
df['급여'].quantile(q=0.25) #25%에 해당하는 급여

np.float64(4453000.0)

In [30]:
df['급여'].quantile(q=0.50) #50%에 해당하는 급여

np.float64(4978000.0)

In [31]:
df['급여'].quantile(q=0.75) #75%에 해당하는 급여

np.float64(6628000.0)

In [32]:
# 급여의 평균과 중위값을 모두 알고 싶다면?
df['급여'].aggregate(['mean','median'])

mean      5.394667e+06
median    4.978000e+06
Name: 급여, dtype: float64

In [35]:
#집계함수 이름을 줄여서 agg()로 계산 가능...소수점 2자리
df['급여'].agg(['mean','median']).round(2)

mean      5394666.67
median    4978000.00
Name: 급여, dtype: float64

In [36]:
# 집계 결과 인덱스명을 지정
df['급여'].agg(급여평균='mean', 급여중위값='median').round(2)

급여평균     5394666.67
급여중위값    4978000.00
Name: 급여, dtype: float64

In [37]:
# 여러 컬룸에 대해 서로다른 집계함수를 수행
df.agg(
    나이평균=('나이', 'mean'),
    몸무게중위= ('몸무게', 'median'),
    급여표준편차= ('급여', 'std')
).round(2)

           나이   몸무게          급여
나이평균    38.71   NaN         NaN
몸무게중위     NaN  73.5         NaN
급여표준편차    NaN   NaN  2086783.81

In [39]:
# 시리즈를 만들면서 각각의 항목을 계산
result= pd.Series({
    '나이평균':df['나이'].mean(),
    '몸무게중위':df['몸무게'].median(),
    '급여표준편차':df['급여'].std(),
}).round(2)
result

나이평균           38.71
몸무게중위          73.50
급여표준편차    2086783.81
dtype: float64

In [40]:
# 집계함수 중 파라미터(인자)가 있어야만 하는 함수 quantile 을 사용하려면 문자열만으로는 불가능하고 람다함수를 만들면 됨
df['급여'].agg([
    'mean',
    'median',
    lambda x:x.quantile(0.25),
    lambda x:x.quantile(0.50),
    lambda x:x.quantile(0.75),
])

mean        5.394667e+06
median      4.978000e+06
<lambda>    4.453000e+06
<lambda>    4.978000e+06
<lambda>    6.628000e+06
Name: 급여, dtype: float64

In [41]:
df['급여'].agg(
    mean='mean',
    mediain='median',
    q1=lambda x:x.quantile(0.25),
    q2=lambda x:x.quantile(0.50),
    q3=lambda x:x.quantile(0.75),
)

mean       5.394667e+06
mediain    4.978000e+06
q1         4.453000e+06
q2         4.978000e+06
q3         6.628000e+06
Name: 급여, dtype: float64

In [42]:
# groupby() + egg()
# 부서별 지출 데이터는 컬룸마다 의미가 다르기에 컬룸별로 다른 집계함수를 쓰는게 자연스러움.

# 부서별 지출 데이터 다시 불러오기
df= pd.read_csv('./data_set/expense_data.csv')
df

         date department employee product  expense_amount  quantity
0  2025-01-01        영업팀      김민수     노트북         1200000         1
1  2025-01-01        영업팀      이서연     마우스           30000         3
2  2025-01-02       마케팅팀      박지훈   온라인광고          500000         1
3  2025-01-02        영업팀      김민수     모니터          400000         1
4  2025-01-03        개발팀      최은지    라이선스          800000         2
5  2025-01-03       마케팅팀      박지훈    이벤트비          200000         1
6  2025-01-04        영업팀      이서연     키보드          100000         2
7  2025-01-04        개발팀      최은지    서버비용         1500000         1
8  2025-01-05        영업팀      김민수     노트북         1200000         1
9  2025-01-05       마케팅팀      박지훈   온라인광고          700000         1

In [44]:
# 컬룸마다 집계하려면 방법이 다를 수 있음.
# 금액은 '규모'
# 수량은 '빈도'
# 제품(항목)은 '다양성'

# 부서별 지출 요약 보고 레포트...
dept_summary= df.groupby('department').agg(
    총지출액=('expense_amount','sum'),    #전체 비용 규모
    평균지출액=('expense_amount','mean'), #지출 패턴
    최고지출액=('expense_amount','max'),  #고액 지출 규모
    총구매수량=('quantity', "sum"),       #구매 빈도
    지출항목= ('product','nunique'),      #취급하는 항목 다양성
    담당직원수= ('employee','nunique')    #직원수 규모 확인..관리 복잡도...
).round(2)

dept_summary

               총지출액       평균지출액    최고지출액  총구매수량  지출항목  담당직원수
department
개발팀         2300000  1150000.00  1500000      3     2      1
마케팅팀        1400000   466666.67   700000      3     2      1
영업팀         2930000   586000.00  1200000      8     4      2

In [47]:
# 건별 평균 지출내역 계산해보기..새로운 컬룸에 계산결과를 할당
df.groupby('department').agg(
    총지출액=('expense_amount','sum'),
    총구매수량=('quantity','sum')
).assign(
    건당평균지출= lambda x:x['총지출액']/x['총구매수량']
)

               총지출액  총구매수량         건당평균지출
department
개발팀         2300000      3  766666.666667
마케팅팀        1400000      3  466666.666667
영업팀         2930000      8  366250.000000

### transform
그룹별로 계산은 하되, 결과를 '원래 행 개수 그대로'유지해 줌.  

- 핵심차이  
agg() : 행 수 줄어듦  
transfrom() : 행 수 그대로 유지.

In [48]:
# agg()
df.groupby('department')['expense_amount'].mean().round()
#부서별로 1행
#원본 데이터와 함계 비교가 안됨

department
개발팀     1150000.0
마케팅팀     466667.0
영업팀      586000.0
Name: expense_amount, dtype: float64

In [49]:
#transform -- 각 행에 '부서 평균 지출' 붙이기
df['부서평균지출']= df.groupby('department')['expense_amount'].transform('mean').round()
df

         date department employee product  expense_amount  quantity     부서평균지출
0  2025-01-01        영업팀      김민수     노트북         1200000         1   586000.0
1  2025-01-01        영업팀      이서연     마우스           30000         3   586000.0
2  2025-01-02       마케팅팀      박지훈   온라인광고          500000         1   466667.0
3  2025-01-02        영업팀      김민수     모니터          400000         1   586000.0
4  2025-01-03        개발팀      최은지    라이선스          800000         2  1150000.0
5  2025-01-03       마케팅팀      박지훈    이벤트비          200000         1   466667.0
6  2025-01-04        영업팀      이서연     키보드          100000         2   586000.0
7  2025-01-04        개발팀      최은지    서버비용         1500000         1  1150000.0
8  2025-01-05        영업팀      김민수     노트북         1200000         1   586000.0
9  2025-01-05       마케팅팀      박지훈   온라인광고          700000         1   466667.0

In [50]:
# 개별 지출이 부서의 평균지출보다 큰가? -- 의심.. 사기..
df.assign(평균초과여부= lambda x:x['expense_amount'] > x['부서평균지출'])

,date,department,employee,product,expense_amount,quantity,부서평균지출,평균초과여부
0,2025-01-01,영업팀,김민수,노트북,1200000,1,586000.0,True
1,2025-01-01,영업팀,이서연,마우스,30000,3,586000.0,False
2,2025-01-02,마케팅팀,박지훈,온라인광고,500000,1,466667.0,True
3,2025-01-02,영업팀,김민수,모니터,400000,1,586000.0,False
4,2025-01-03,개발팀,최은지,라이선스,800000,2,1150000.0,False
5,2025-01-03,마케팅팀,박지훈,이벤트비,200000,1,466667.0,False
6,2025-01-04,영업팀,이서연,키보드,100000,2,586000.0,False
7,2025-01-04,개발팀,최은지,서버비용,1500000,1,1150000.0,True
8,2025-01-05,영업팀,김민수,노트북,1200000,1,586000.0,True
9,2025-01-05,마케팅팀,박지훈,온라인광고,700000,1,466667.0,True

In [52]:
# 이상 지출 탐지( z-score : 표준점수 -너의 편차가 표준편차에 비해 얼마나 차이가 있는지 [(원점수-평균)/표준편차] )
df.assign(
    z_score= lambda x:
        (x['expense_amount']-x.groupby('department')['expense_amount'].transform('mean'))/x.groupby('department')['expense_amount'].transform('std')
)

,date,department,employee,product,expense_amount,quantity,부서평균지출,z_score
0,2025-01-01,영업팀,김민수,노트북,1200000,1,586000.0,1.063245
1,2025-01-01,영업팀,이서연,마우스,30000,3,586000.0,-0.962808
2,2025-01-02,마케팅팀,박지훈,온라인광고,500000,1,466667.0,0.132453
3,2025-01-02,영업팀,김민수,모니터,400000,1,586000.0,-0.322091
4,2025-01-03,개발팀,최은지,라이선스,800000,2,1150000.0,-0.707107
5,2025-01-03,마케팅팀,박지훈,이벤트비,200000,1,466667.0,-1.059626
6,2025-01-04,영업팀,이서연,키보드,100000,2,586000.0,-0.841592
7,2025-01-04,개발팀,최은지,서버비용,1500000,1,1150000.0,0.707107
8,2025-01-05,영업팀,김민수,노트북,1200000,1,586000.0,1.063245
9,2025-01-05,마케팅팀,박지훈,온라인광고,700000,1,466667.0,0.927173

In [53]:
# z-score 해석
# 0 부서 평균과 같음
# 1 평균보다 1표준편차 큰 지출
#-1 평균보다 1표준편차 적은 지출

# z-score는 금액의 크기가 아니라 부서 지출 기준으로 볼때 상대적인 사용 정도를 보여주는 값!

In [56]:
# 표준편차만으로는 올바른 분산의 정도를 파악하지 못할 수 있음.
# --> 변동계수 CV = 표준편차 / 평균 * 100
# 두 종류의 자료값이 차이가 있을때 단순하게 표준편차를 통해 분산정도를 파악할 수 없음.

#예) 성인여성 50명, 10세 소녀 50명을 대상으로 몸무게를 조사한 결과..

# 성인여성 : 평균[51.1kg], 표준편차[5.0kg]
# 10세소녀 : 평균[26.49kg], 표준편차[3.66kg]

# 표준편차만 보면 성인여성 표본집단의 몸무게 변동이 커 보임..
df= pd.DataFrame({
    '평균':[51.1, 26.49],
    '표준편차':[5.0, 3.66]
}, index=['성인여성','10세소녀'])
df

          평균  표준편차
성인여성   51.10  5.00
10세소녀  26.49  3.66

In [57]:
# 변동계수 계산... --파생지표 추가
df['변동계수']= (df['표준편차']/df['평균'])*100
df

          평균  표준편차       변동계수
성인여성   51.10  5.00   9.784736
10세소녀  26.49  3.66  13.816535

filter 함수 - 컬룸 이름을 기준으로 데이터를 선택하는 기능

In [58]:
df = pd.DataFrame({
    '이름': ['김민수', '이서연'],
    '급여': [6000000, 4200000],
    '보너스': [500000, 300000],
    '입사연도': [2018, 2021]
})
df

    이름       급여     보너스  입사연도
0  김민수  6000000  500000  2018
1  이서연  4200000  300000  2021

In [59]:
# 급여 관련 컬룸만 확인
df.filter(items=['급여','보너스'])

        급여     보너스
0  6000000  500000
1  4200000  300000

In [60]:
# [] 인덱싱으로 가능했었음.. 이거 왜??
df[['급여','보너스']]

        급여     보너스
0  6000000  500000
1  4200000  300000

In [61]:
# 다른점.. like 사용 가능 (특정 글자가 있기만 하면..)
df.filter(like='급')

        급여
0  6000000
1  4200000

In [62]:
#정규표현으로도 추출 가능
df.filter(regex='급여|보너스')

        급여     보너스
0  6000000  500000
1  4200000  300000

## 그룹에서 표본샘플 추출

In [63]:
#예) 여행지를 추출하는 서비스 개발을 위해 성별이나 나이에 따라 여행지 선호를 분석하기!!

# 성별과 나이에 따른 여행지 선호 설문 데이터
df= pd.read_csv('./data_set/travel_preference_survey.csv')
df

    번호  성별  나이  선호도시 여행스타일
0    1  남성  25    일본  자유여행
1    2  여성  23   프랑스  배낭여행
2    3  남성  32   베트남   패키지
3    4  여성  29  이탈리아  자유여행
4    5  남성  41    태국    휴양
5    6  여성  35    일본  자유여행
6    7  남성  27    미국  로드트립
7    8  여성  31   스페인  문화여행
8    9  남성  36   베트남  자유여행
9   10  여성  28    태국    휴양
10  11  남성  22    일본  배낭여행
11  12  여성  34   프랑스   패키지
12  13  남성  45  이탈리아  문화여행
13  14  여성  26   베트남  자유여행
14  15  남성  39    미국  로드트립
15  16  여성  42   스페인  문화여행
16  17  남성  30    태국    휴양
17  18  여성  24    일본  배낭여행
18  19  남성  34   프랑스  자유여행
19  20  여성  37  이탈리아   패키지
20  21  남성  28    일본  자유여행
21  22  여성  23    일본  배낭여행
22  23  남성  35   베트남    휴양
23  24  여성  29   프랑스  자유여행
24  25  남성  42    미국  로드트립
25  26  여성  34   베트남  자유여행
26  27  남성  31    태국  자유여행
27  28  여성  27    태국    휴양
28  29  남성  26    일본  배낭여행
29  30  여성  31  이탈리아  문화여행
30  31  남성  38   프랑스  문화여행
31  32  여성  36    미국  자유여행
32  33  남성  29   베트남   패키지
33  34  여성  25    일본  배낭여행
34  35  남성  45  이탈리아  문화여행
35  36  여성  38   스페인  문화여행
36  37  남성  33    미국  자유여행
37  38  여성  42   프랑스   패키지
38  39  남성  41    태국    휴양
39  40  여성  33   베트남  자유여행
40  41  남성  24    일본  배낭여행
41  42  여성  28    태국    휴양
42  43  남성  36   스페인  문화여행
43  44  여성  35  이탈리아  자유여행
44  45  남성  39   프랑스  자유여행
45  46  여성  41    미국  로드트립
46  47  남성  27   베트남  자유여행
47  48  여성  26    일본  배낭여행
48  49  남성  44    미국  로드트립
49  50  여성  30   스페인  문화여행
50  51  남성  32    태국    휴양
51  52  여성  37   프랑스  자유여행
52  53  남성  34  이탈리아   패키지
53  54  여성  24   베트남  자유여행
54  55  남성  40   스페인  문화여행
55  56  여성  32    태국    휴양
56  57  남성  30    미국  로드트립
57  58  여성  39  이탈리아   패키지
58  59  남성  34   베트남  자유여행
59  60  여성  43    미국  로드트립

In [67]:
# 성별 별로 3명씩 랜덤 샘플 추출
gender_sample= df.groupby('성별').sample(n=3, random_state=42)
gender_sample

    번호  성별  나이 선호도시 여행스타일
54  55  남성  40  스페인  문화여행
30  31  남성  38  프랑스  문화여행
46  47  남성  27  베트남  자유여행
1    2  여성  23  프랑스  배낭여행
11  12  여성  34  프랑스   패키지
41  42  여성  28   태국    휴양

In [68]:
# 모집단의 데이터가 많지만 3명 이라고 고정하는 것보다 비율로 추출하는 것이 더 합리적..
gender_sample= df.groupby('성별').sample(frac=0.3, random_state=42) #30%
gender_sample

    번호  성별  나이  선호도시 여행스타일
54  55  남성  40   스페인  문화여행
30  31  남성  38   프랑스  문화여행
46  47  남성  27   베트남  자유여행
34  35  남성  45  이탈리아  문화여행
16  17  남성  30    태국    휴양
18  19  남성  34   프랑스  자유여행
56  57  남성  30    미국  로드트립
48  49  남성  44    미국  로드트립
24  25  남성  42    미국  로드트립
1    2  여성  23   프랑스  배낭여행
11  12  여성  34   프랑스   패키지
41  42  여성  28    태국    휴양
53  54  여성  24   베트남  자유여행
27  28  여성  27    태국    휴양
15  16  여성  42   스페인  문화여행
43  44  여성  35  이탈리아  자유여행
21  22  여성  23    일본  배낭여행
25  26  여성  34   베트남  자유여행

In [69]:
# 다중 인덱스
# 성별별로 여행지 선호도...
# 성별 + 여행지 조합하여 응답 수?
# 성별 + 여행스타일 별 평균 나이?

# 이때 사용하는 것이 다중 인덱스

In [70]:
# 성별 + 여행지 응답 수 
result= df.groupby(['성별','선호도시']).size()
result

성별  선호도시
남성  미국      6
    베트남     6
    스페인     2
    이탈리아    3
    일본      5
    태국      5
    프랑스     3
여성  미국      3
    베트남     4
    스페인     4
    이탈리아    5
    일본      5
    태국      4
    프랑스     5
dtype: int64

In [71]:
# 시리즈를 데이터프레임으로 변환
result= result.to_frame('인원수')
result

         인원수
성별 선호도시
남성 미국      6
   베트남     6
   스페인     2
   이탈리아    3
   일본      5
   태국      5
   프랑스     3
여성 미국      3
   베트남     4
   스페인     4
   이탈리아    5
   일본      5
   태국      4
   프랑스     5

In [72]:
# 인덱스를 이용하여 특덩 그룹을 선택하여 분석가능
result.loc['남성']

      인원수
선호도시
미국      6
베트남     6
스페인     2
이탈리아    3
일본      5
태국      5
프랑스     3

In [73]:
result.loc[('여성','일본')] #튜플로 다중 인덱싱!

인원수    5
Name: (여성, 일본), dtype: int64

In [76]:
pd.pivot_table(
    df,
    index='성별',
    columns='여행스타일',
    values='나이',
    aggfunc='mean',
)

여행스타일  로드트립  문화여행  배낭여행       자유여행        패키지     휴양
성별
남성     36.4  40.8  24.0  31.888889  31.666667  35.80
여성     42.0  34.4  24.2  31.800000  38.000000  28.75

In [77]:
# 남성, 여성 모두 어릴때는 '배낭여행' 선호
# 남성은 나이가 많을 수록 '문화여행' -- 나라,도시 역사,예술..생활문화 체험 목적...
# 여성은 나이가 많을 수록 '로드트립' -- 자동차로 이동하면서 여러 도시,장소 둘러보는 여행을 선호

In [78]:
# 데이터를 분석하려면 데이터프레입을 결합하고. 조작하고..파생변수 만들고..피봇해 가면서 여러 관점으로 분석하는 것임.

## 수행과제 06,07,08 챕터 읽고 예제 따라하기