## 결측치
- 결측치(Missing Values)란 데이터셋에서 일부 값이 누락된 것
- 결측치가 있으면 데이터분석 결과를 왜곡할 수 있기에 분석전에 미리 전처리 해 놓아야 함.

In [2]:
import pandas as pd
df = pd.read_csv('./data_set/pandas.csv', encoding='cp949') #제공한 csv 파일이 'cp949'로 되어 있음.
df

    번호   성명  나이    몸무게         급여
0  100  김민재  27   75.0  5428000.0
1  101  이강인  22   57.0        NaN
2  102  박찬호  50   91.0  8428000.0
3  103  차범근  70    NaN  4428000.0
4  104  추신수  43  100.0  4528000.0
5  105  손흥민  31   72.0  7028000.0
6  106  황희찬  28   69.0  2528000.0

In [4]:
# 결측치 존재 확인
df.isna() # 각 cell마다 결측치 여부를 알려줌. 데이터프레임으로 결과 줌

      번호     성명     나이    몸무게     급여
0  False  False  False  False  False
1  False  False  False  False   True
2  False  False  False  False  False
3  False  False  False   True  False
4  False  False  False  False  False
5  False  False  False  False  False
6  False  False  False  False  False

In [5]:
df.isnull()

      번호     성명     나이    몸무게     급여
0  False  False  False  False  False
1  False  False  False  False   True
2  False  False  False  False  False
3  False  False  False   True  False
4  False  False  False  False  False
5  False  False  False  False  False
6  False  False  False  False  False

In [6]:
# 결측치의 개수 확인
df.isna().sum()

번호     0
성명     0
나이     0
몸무게    1
급여     1
dtype: int64

In [7]:
# 결측치의 비율이 별로 없다면 보통은 그 행을 제거한 후 분석을 함.
# 결측치의 비율 확인 - 산수
(df.isnull().mean()*100).round(2)

번호      0.00
성명      0.00
나이      0.00
몸무게    14.29
급여     14.29
dtype: float64

In [9]:
# 몸무게 컬룸에서 결측치가 존재하는 행을 필터링하여 추출
df[ df['몸무게'].isna() ] #불리언 인덱싱

    번호   성명  나이  몸무게         급여
3  103  차범근  70  NaN  4428000.0

In [10]:
# '몸무게', '급여' 컬룸의 결측치가 존재하는 행을 추출
df[  df['몸무게'].isnull() | df['급여'].isna()  ]

    번호   성명  나이   몸무게         급여
1  101  이강인  22  57.0        NaN
3  103  차범근  70   NaN  4428000.0

In [11]:
# 반대로 결측치가 없는 행들만 추출
df[ df['몸무게'].notna() & df['급여'].notnull() ]

    번호   성명  나이    몸무게         급여
0  100  김민재  27   75.0  5428000.0
2  102  박찬호  50   91.0  8428000.0
4  104  추신수  43  100.0  4528000.0
5  105  손흥민  31   72.0  7028000.0
6  106  황희찬  28   69.0  2528000.0

## 결측치 처리 방법 9가지

In [12]:
#1. 결측치가 존재하는 컬룸을 계산해서 제외하기 위해 제거 drop
df.drop(columns= ['몸무게','급여']) #원본은 안바뀜

    번호   성명  나이
0  100  김민재  27
1  101  이강인  22
2  102  박찬호  50
3  103  차범근  70
4  104  추신수  43
5  105  손흥민  31
6  106  황희찬  28

In [14]:
# 위 방법은 몸무게와 급여 컬룸이 필요없을때..중요한 변수가 아닐때..
# 컬룸 제거 말고.. 결측치를 가진 관측값(행row)을 제거
df.drop(index=[1,3])

    번호   성명  나이    몸무게         급여
0  100  김민재  27   75.0  5428000.0
2  102  박찬호  50   91.0  8428000.0
4  104  추신수  43  100.0  4528000.0
5  105  손흥민  31   72.0  7028000.0
6  106  황희찬  28   69.0  2528000.0

In [15]:
# 행의 index 번호를 찾기 어려우니..결측치가 있는 행을 알아서 찾아서 제거..
df.dropna()

    번호   성명  나이    몸무게         급여
0  100  김민재  27   75.0  5428000.0
2  102  박찬호  50   91.0  8428000.0
4  104  추신수  43  100.0  4528000.0
5  105  손흥민  31   72.0  7028000.0
6  106  황희찬  28   69.0  2528000.0

In [17]:
#2. 0으로 채우기
df.fillna(0) #결측값을 찾아서 0으로 채워줌.

    번호   성명  나이    몸무게         급여
0  100  김민재  27   75.0  5428000.0
1  101  이강인  22   57.0        0.0
2  102  박찬호  50   91.0  8428000.0
3  103  차범근  70    0.0  4428000.0
4  104  추신수  43  100.0  4528000.0
5  105  손흥민  31   72.0  7028000.0
6  106  황희찬  28   69.0  2528000.0

In [19]:
#3. 평균값으로 채우기 -- 몸무게 컬룸만
df[['몸무게']].fillna( df['몸무게'].mean() )

          몸무게
0   75.000000
1   57.000000
2   91.000000
3   77.333333
4  100.000000
5   72.000000
6   69.000000

In [20]:
#4. 중위값 채우기 -- 급여
df[['급여']].fillna(df['급여'].median())

          급여
0  5428000.0
1  4978000.0
2  8428000.0
3  4428000.0
4  4528000.0
5  7028000.0
6  2528000.0

## 사례별 결측치 처리 방법

In [22]:
#1. 제거가 합리적인 상황 -- 설문조사 만족도 평균
df = pd.read_csv('./data_set/결측치 처리/1.survey_score.csv')
df

    응답자ID  나이  만족도점수
0  RES001  23    4.0
1  RES002  25    5.0
2  RES003  31    3.0
3  RES004  28    NaN
4  RES005  35    4.0
5  RES006  42    5.0
6  RES007  29    4.0

In [24]:
#결측치 확인
df.isnull().sum()

응답자ID    0
나이       0
만족도점수    1
dtype: int64

In [25]:
# 전체 데이터 대비 결측 비율 확인
(df.isnull().mean()*100).round(2)

응답자ID     0.00
나이        0.00
만족도점수    14.29
dtype: float64

In [26]:
# 응답자 중 1명을 제거해도 전체 만족도에 큰 영향 없음.
df_drop = df.dropna()
df_drop

    응답자ID  나이  만족도점수
0  RES001  23    4.0
1  RES002  25    5.0
2  RES003  31    3.0
4  RES005  35    4.0
5  RES006  42    5.0
6  RES007  29    4.0

In [29]:
# 전체 만족도 평균
print('만족도 점수:', df_drop['만족도점수'].mean().round(1))

만족도 점수: 4.2

In [37]:
#2. 0으로 채우기 - 구매금액..
df= pd.read_csv('./data_set/결측치 처리/2.purchase_amount.csv')
df

   고객ID  방문횟수      구매금액
0  C001     5  120000.0
1  C002     3       NaN
2  C003     1   30000.0
3  C004     2       NaN
4  C005     4   80000.0

In [39]:
df['구매금액']= df['구매금액'].fillna(0)
df

   고객ID  방문횟수      구매금액
0  C001     5  120000.0
1  C002     3       0.0
2  C003     1   30000.0
3  C004     2       0.0
4  C005     4   80000.0

In [40]:
# 방문횟수에 따른 구매금액 분석
df['구매금액'].sum()/df['방문횟수'].sum()

np.float64(15333.333333333334)

In [43]:
#3. 평균으로 채우기 -- 시험성적(결측값이 반의 평균에 근접. 정규분포...가정)
df= pd.read_csv('./data_set/결측치 처리/3.exam_score.csv')
df

  학생ID  수학점수
0  S01  78.0
1  S02  85.0
2  S03  90.0
3  S04   NaN
4  S05  82.0
5  S06  88.0

In [44]:
# 평균으로 결측값으로 채우기 -- 표본데이터가 많을 수록 정규분포에 가까워짐.
mean_score= df['수학점수'].mean()
df['수학점수']=df['수학점수'].fillna(mean_score)
df

  학생ID  수학점수
0  S01  78.0
1  S02  85.0
2  S03  90.0
3  S04  84.6
4  S05  82.0
5  S06  88.0

In [45]:
# 기초 통계 분석
df['수학점수'].describe()

count     6.000000
mean     84.600000
std       4.270831
min      78.000000
25%      82.650000
50%      84.800000
75%      87.250000
max      90.000000
Name: 수학점수, dtype: float64

In [53]:
#4. 결측치를 중앙값으로 채우기 ( 왜도(이상치 데이터)가 있을때.. 월소득 )
df = pd.read_csv('./data_set/결측치 처리/4.income.csv')
df

  개인ID      월소득
0  P01   2500.0
1  P02   2700.0
2  P03   3000.0
3  P04      NaN
4  P05   2800.0
5  P06  15000.0

In [54]:
# 데이터에 이상치(outlier)가 있는지 여부 - 탐지방식 : IQR(사분위), z-score 등

#방법1. z-score 가 3이상 
#표준점수(z-score) = (데이터-평균:내 편차)/표준편차  > 3 면 이상함.
( df['월소득']-df['월소득'].mean() ) / df['월소득'].std()
# 기준 의미
# |z-score| > 3 이상치(처리 대상)
# |z-score| > 2 약간 이상치(관심)
# |z-score| > 1 양호한 수준

# |z-score| 만으로 모든 이상치를 탐지하지 못할 수 있음..IQR도 함께 검정.

0   -0.492581
1   -0.456094
2   -0.401362
3         NaN
4   -0.437850
5    1.787887
Name: 월소득, dtype: float64

In [55]:
#방법2. IQR(Inter Quartile Range) 규칙
# IQR = Q3-Q1
# 이상치의 하안선 : Q1 - 1.5*IQR
# 이상치의 상한선 : Q3 + 1.5*IQR
Q1 = df['월소득'].quantile(0.25)
Q3 = df['월소득'].quantile(0.75)
IQR= Q3-Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

lower, upper

(np.float64(2250.0), np.float64(3450.0))

In [57]:
df[ (df['월소득']<lower) | (df['월소득']>upper) ]
#고소득 이상치 존재... -- 평균이 왜곡됨

  개인ID      월소득
5  P06  15000.0

In [58]:
#이상치가 있을때.. 결측치 채우는 방법 - 중위값
df['월소득'] = df['월소득'].fillna( df['월소득'].median() )
df

  개인ID      월소득
0  P01   2500.0
1  P02   2700.0
2  P03   3000.0
3  P04   2800.0
4  P05   2800.0
5  P06  15000.0

In [59]:
#4. 최빈값(빈독수가 많음)으로 채우기 -- 범주형 데이터일때..유용
df= pd.read_csv('./data_set/결측치 처리/5.customer_gender.csv')
df

  고객ID   성별
0  C01    M
1  C02    F
2  C03    M
3  C04  NaN
4  C05    M
5  C06    F

In [60]:
# 성별중에서 더 많은 성별이 누군지 판별...
mode_gender = df['성별'].mode()
mode_gender

0    M
Name: 성별, dtype: object

In [61]:
df['성별'] = df['성별'].fillna(mode_gender[0])
df

  고객ID 성별
0  C01  M
1  C02  F
2  C03  M
3  C04  M
4  C05  M
5  C06  F

In [62]:
# 6. 그룹별 대체 -- 실무에서 가장 많이 사용. 전체평균/중앙값 이 아니라..그룹 내 평균/중앙값 사용
df= pd.read_csv('./data_set/결측치 처리/6.group_income.csv')
df

   ID 성별      소득
0   1  M  3200.0
1   2  M     NaN
2   3  M  3500.0
3   4  F  2800.0
4   5  F     NaN
5   6  F  2900.0

In [64]:
# 성별에 따른 소득이 다른 경향이 있기에..이를 반영...
df['소득'] = df['소득'].fillna( df.groupby('성별')['소득'].transform('mean') )
df

   ID 성별      소득
0   1  M  3200.0
1   2  M  3350.0
2   3  M  3500.0
3   4  F  2800.0
4   5  F  2850.0
5   6  F  2900.0

In [65]:
#7. 예측모델 기반 대체...
df= pd.read_csv('./data_set/결측치 처리/7.house_price.csv')
df

  주택ID  면적  방개수        가격
0  H01  45    2  220000.0
1  H02  60    3  300000.0
2  H03  75    3       NaN
3  H04  80    4  420000.0
4  H05  50    2  250000.0

In [66]:
# 가격을 결정하는 요인이 다른 집들의 가격보다.. 내집의 특성들(면적, 방개수)에 의해 결정되는 데이터
# 가격의 요인이 된 특성값들과의 관계성을 파악!
# 면적,방개수에 따라 가격이 어떻게 형성되는지를 파악하고 이를 기반으로 결측값을 채우기
# 단순 비율로 예측하기 어려움..
# 그러니..이 비율을 머신러닝 알고리즘을 이용하여 찾도록....
# 이때 사용하는 알고리즘. [선형회귀 알고리즘]

# 용어
# 값을 결정하는 특성(요인)값을 '독립변수'라고 부름.
# 요인(특성)에 의해 결정되는 값을 '종족변수' 라고 부름 (우리가 찾고자하는 결과(예측)값)

# 머신러닝 알고리즘을 이용하여 독립변수(면적,방개수)에 따른 종족변수(가격)을 예측할 수 있음.

# 기존 (면적,방개수)에 따른 (가격) 정보를 머신러닝 알고리즘으로 훈련(학습)하면 그 패턴을 찾아냄
# 그 패턴을 기반으로 새로운 (면적, 방개수)를 주었을때 (가격)을 예측해줌.

In [69]:
# 머신러닝 알고리즘에 훈련시킬 데이터 추출 (결측치가 없는 데이터)
train_df = df.dropna()

#2. 예측하고자 하는 데이터 추출 ( 종속변수가 비어있는 데이터 )
test_df= df[ df['가격'].isnull() ]

In [70]:
#3. 선형회귀 알고리즘을 구현한 모델 사용 [대표적인 머신러닝 모듈 scikit learn]
from sklearn.linear_model import LinearRegression

# 선형회귀 모델 객체 생성
model= LinearRegression()

# 모델 훈련
model.fit(train_df[['면적','방개수']], train_df['가격']) #(독립변수(요인), 종속변수(결과))

# 학습된 모델에게 예측을 원하는 데이터의 독립변수(특성값들)를 주면 종속변수값을 예측해줌
prices= model.predict( test_df[['면적','방개수']] )
print(prices)

[401000.]

In [71]:
#결측값을 이 예측값으로 채우기
df['가격'].fillna(prices[0])

0    220000.0
1    300000.0
2    401000.0
3    420000.0
4    250000.0
Name: 가격, dtype: float64

In [72]:
# 모델의 예측값을 검증1. 이미 알고있는 정답데이터에 적용
# 0 H01 45   2   220000.0
# 1 H02 60   3   300000.0
model.predict( train_df[['면적','방개수']] ) #훈련용 데이터셋으로 확인하여 예측값과 실제값 비교

array([218000., 302000., 419000., 251000.])

In [74]:
#면적과 가격사이의 상관관계 정도를 알 수 있음. 상관계수 (1이면 완전 관련있는것)
df[['면적','방개수','가격']].corr()

           면적       방개수        가격
면적   1.000000  0.921038  0.999365
방개수  0.921038  1.000000  0.978282
가격   0.999365  0.978282  1.000000

In [75]:
#8. 시계열 데이터 보관 - 주식, 센서데이터, 온도 ...
df = pd.read_csv('./data_set/결측치 처리/8.temperature_timeseries.csv')
df

           날짜    온도
0  2024-01-01  18.2
1  2024-01-02  18.5
2  2024-01-03   NaN
3  2024-01-04  19.1
4  2024-01-05  19.3

In [76]:
#앞 뒤 데이터를 기반으로 결측값 예측. 보관
df['온도']=df['온도'].interpolate()
df

           날짜    온도
0  2024-01-01  18.2
1  2024-01-02  18.5
2  2024-01-03  18.8
3  2024-01-04  19.1
4  2024-01-05  19.3

In [77]:
# 이전 행과의 차이
df['온도'].diff()

0    NaN
1    0.3
2    0.3
3    0.3
4    0.2
Name: 온도, dtype: float64

In [78]:
#9. 결측 여부 자체를 변수로 사용 - 결측치 자체가 정보. 대출심사에서 소득 미기입.
df = pd.read_csv('./data_set/결측치 처리/9.loan_application.csv')
df

  신청자ID      소득 대출승인여부
0   A01  3200.0      Y
1   A02     NaN      N
2   A03  2800.0      Y
3   A04     NaN      N
4   A05  4000.0      Y

In [79]:
# 데이터가 없는 것 자체가 결과값(대출승인여부)에 요인이 되는 것이라..별도의 채우는 조치 안함.
# 대신 결측값을 머신러닝같은 모델에게는 훈련데이터가 되지 않기에..
# yes, no를 의미하는 파생변수를 새로 추가하여 이를 학습하도록 처리함.
df['소득_결측여부']=df['소득'].isnull().astype(int) #True->1, False=0
df

  신청자ID      소득 대출승인여부  소득_결측여부
0   A01  3200.0      Y        0
1   A02     NaN      N        1
2   A03  2800.0      Y        0
3   A04     NaN      N        1
4   A05  4000.0      Y        0

In [80]:
# 교차표를 만들어주는 기능함수
pd.crosstab(df['소득_결측여부'], df['대출승인여부'])

대출승인여부   N  Y
소득_결측여부
0        0  3
1        2  0